import './account.dart';
import './category.dart';
import './recurrence.dart';
import './transfer.dart';
import './planned_transaction.dart';

final ACCOUNTS = [
  Account(
    id: 1,
    accountName: 'Nationwide',
    description: 'Main account',
    balance: 2116.0,
    usedForCashFlow: true,
    usedForSummary: false,
  ),
  Account(
    id: 2,
    accountName: 'Atom Bank PLC',
    description: 'mortgage out of this account',
    balance: 2150.0,
    usedForCashFlow: true,
    usedForSummary: false,
  ),
  Account(
    id: 3,
    accountName: 'Bank of Baroda',
    description: 'to pay mobile costs',
    balance: 2880.0,
    usedForCashFlow: true,
    usedForSummary: false,
  ),
   Account(
    id: 4,
    accountName: 'Bank of Savings',
    description: 'Where we save our money',
    balance: 500.0,
    usedForCashFlow: true,
    usedForSummary: false,
  ),
];
final CATEGORIES = [
  Category(
    id: 1,
    categoryName: 'Rent',
    iconPath: 'assets/images/category_icons/c008.jpg',
    description: 'Payment for accomodation',
    
    useForCashFlow: true,
  ),
    Category(
    id: 2,
    categoryName: 'Mortgage',
    description: 'Payment for property',
    iconPath: 'assets/images/category_icons/c144.jpg',
    useForCashFlow: true,
  ),
    Category(
    id: 3,
    categoryName: 'Running Costs',
    description: 'Cost of running something',
    iconPath: 'assets/images/category_icons/c051.jpg',
    useForCashFlow: true,
  ),
    Category(
    id: 4,
    categoryName: 'Cleaning',
    description: 'Cost of cleaning contract',
    iconPath: 'assets/images/category_icons/c034.jpg',
    useForCashFlow: true,
  ),
    Category(
    id: 5,
    categoryName: 'Boiler Service',
    description: 'Annual boiler service cost',
    iconPath: 'assets/images/category_icons/c031.jpg',
    useForCashFlow: true,
  ),
    Category(
    id: 6,
    categoryName: 'Holiday',
    description: 'Holiday cost',
    iconPath: 'assets/images/category_icons/c142.jpg',
    useForCashFlow: true,
  ),
    Category(
    id: 7,
    categoryName: 'Car Costs',
    description: 'Car Loan etc',
    iconPath: 'assets/images/category_icons/c146.jpg',
    useForCashFlow: true,
  ), 
    Category(
    id: 8,
    categoryName: 'Petrol',
    description: 'petrol costs',
    iconPath: 'assets/images/category_icons/c033.jpg',
    useForCashFlow: true,
  ), 
    Category(
    id: 9,
    categoryName: 'Savings',
    description: 'loans charges etc',
    iconPath: 'assets/images/category_icons/c019.jpg',
    useForCashFlow: true,
  ),  
    Category(
    id: 10,
    categoryName: 'Living Expenses',
    description: 'from experience',
    iconPath: 'assets/images/category_icons/c145.jpg',
    useForCashFlow: true,
  ), 
    Category(
    id: 11,
    categoryName: 'Car Loan',
    description: 'paying for the car',
    iconPath: 'assets/images/category_icons/c090.jpg',
    useForCashFlow: true,
  ), 
    Category(
    id: 12,
    categoryName: 'Car Insurance',
    description: 'to insure the car each year',
    iconPath: 'assets/images/category_icons/c112.jpg',
    useForCashFlow: true,
  ),    
];
final RECURRENCE = [
  Recurrence(
    id: 1,
    title: 'Weekly',
    description: 'more',
    iconPath: 'assets/images/recurrence_icons/r052.jpg',
    type: 0,
    noOccurences: 0,
  ),
    Recurrence(
    id: 2,
    title: 'Monthly',
    description: 'more',
    iconPath: 'assets/images/recurrence_icons/r003.jpg',
    type: 1,
    noOccurences: 0,
  ),
    Recurrence(
    id: 3,
    title: 'Quarterly',
    description: 'more',
    iconPath: 'assets/images/recurrence_icons/r064.jpg',
    type: 2,
    noOccurences: 0,
  ),
    Recurrence(
    id: 4,
    title: 'Yearly',
    description: 'more',
    iconPath: 'assets/images/recurrence_icons/r065.jpg',
    type: 3,
    noOccurences: 0,
  ),
      Recurrence(
    id: 5,
    title: 'Weekly Occurr',
    description: 'more',
    iconPath: 'assets/images/recurrence_icons/r061.jpg',
    type: 0,
    noOccurences: 5,
  ),
      Recurrence(
    id: 6,
    title: 'Monthly Occur',
    description: 'more',
    iconPath: 'assets/images/recurrence_icons/r054.jpg',
    type: 1,
    noOccurences: 15,
  ),
      Recurrence(
    id: 7,
    title: 'Quarterly Occurr',
    description: 'more',
    iconPath: 'assets/images/recurrence_icons/r066.jpg',
    type: 2,
    noOccurences: 5,
  ),
      Recurrence(
    id: 8,
    title: 'Yearly Occurr',
    description: 'more',
    iconPath: 'assets/images/recurrence_icons/r067.jpg',
    type: 3,
    noOccurences: 5,
  ),
      Recurrence(
    id: 9,
    title: 'Weekly EndDate',
    description: 'more',
    iconPath: 'assets/images/recurrence_icons/r063.jpg',
    type: 0,
    noOccurences: 0,
    endDate: '2019-10-10T00:00:00.000000',
  ),
    Recurrence(
    id: 10,
    title: 'Monthly EndDate',
    description: 'more',
    iconPath: 'assets/images/recurrence_icons/r019.jpg',
    type: 1,
    noOccurences: 0,
    endDate: '2019-10-10T00:00:00.000000',
  ),
      Recurrence(
    id: 11,
    title: 'Quarterly EndDate',
    description: 'more',
    iconPath: 'assets/images/recurrence_icons/r021.jpg',
    type: 2,
    noOccurences: 0,
    endDate: '2019-10-10T00:00:00.000000',
  ),
      Recurrence(
    id: 12,
    title: 'Yearly EndDate',
    description: 'more',
    iconPath: 'assets/images/recurrence_icons/r062.jpg',
    type: 3,
    noOccurences: 0,
    endDate: '2019-10-10T00:00:00.000000',
  ),
           
];

final PLANNEDTRANSACTION = [
  PlannedTransaction(
    id: 1,
    title: 'Phil A',
    description: 'Monthly Rent',
    accountId: 1,
    recurrenceId: 2,
    categoryId: 1,
    amount: 650.0,
    credit: true, 
    plannedDate: '2019-09-02T00:00:00.000000',
    useForCashFlow: true,
  ),
  PlannedTransaction(
    id: 2,
    title: 'Jayne A',
    description: 'Monthly Rent',
    accountId: 1,
    recurrenceId: 2,
    categoryId: 1,
    amount: 560.0,
    credit: true, 
    plannedDate: '2019-09-05T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 3,
    title: 'Sharon A',
    description: 'Monthly Rent',
    accountId: 1,
    recurrenceId: 2,
    categoryId: 1,
    amount: 720.0,
    credit: true, 
    plannedDate: '2019-09-10T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 4,
    title: 'Gill A',
    description: 'Monthly Rent',
    accountId: 1,
    recurrenceId: 2,
    categoryId: 1,
    amount: 460.0,
    credit: true, 
    plannedDate: '2019-10-12T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 5,
    title: 'Gas A',
    description: 'Gas Bill House A',
    accountId: 1,
    recurrenceId: 2,
    categoryId: 3,
    amount: 30.0,
    credit: false, 
    plannedDate: '2019-10-03T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 6,
    title: 'Electric A',
    description: 'Electric Bill House A',
    accountId: 1,
    recurrenceId: 2,
    categoryId: 3,
    amount: 45.0,
    credit: false, 
    plannedDate: '2019-10-04T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 7,
    title: 'Internet A',
    description: 'Internet House A',
    accountId: 1,
    recurrenceId: 2,
    categoryId: 3,
    amount: 20.0,
    credit: false, 
    plannedDate: '2019-10-12T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 8,
    title: 'Council Tax A',
    description: 'Council Tax House A',
    accountId: 1,
    recurrenceId: 2,
    categoryId: 3,
    amount: 95.0,
    credit: false, 
    plannedDate: '2019-10-18T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 9,
    title: 'Water Rates A',
    description: 'Water Rates House A',
    accountId: 1,
    recurrenceId: 2,
    categoryId: 3,
    amount: 56.0,
    credit: false, 
    plannedDate: '2019-10-01T00:00:00.000000',
    useForCashFlow: true,
  ),
  PlannedTransaction(
    id: 10,
    title: 'Cleaning A',
    description: 'Cleaning House A',
    accountId: 1,
    recurrenceId: 1,
    categoryId: 4,
    amount: 30.0,
    credit: false, 
    plannedDate: '2019-10-07T00:00:00.000000',
    useForCashFlow: true,
  ), 
  PlannedTransaction(
    id: 11,
    title: 'Mortgage A',
    description: 'Mortgage for House A',
    accountId: 1,
    recurrenceId: 2,
    categoryId: 2,
    amount: 1500.0,
    credit: false, 
    plannedDate: '2019-10-28T00:00:00.000000',
    useForCashFlow: true,
  ), 
  PlannedTransaction(
    id: 12,
    title: 'Boiler Service A',
    description: 'Boiler Service A',
    accountId: 1,
    recurrenceId: 4,
    categoryId: 5,
    amount: 200.0,
    credit: false, 
    plannedDate: '2019-10-01T00:00:00.000000',
    useForCashFlow: true,
  ), 
  PlannedTransaction(
    id: 13,
    title: 'Angela B',
    description: 'Monthly Rent',
    accountId: 2,
    recurrenceId: 2,
    categoryId: 1,
    amount: 700.0,
    credit: true, 
    plannedDate: '2019-09-03T00:00:00.000000',
    useForCashFlow: true,
  ),
  PlannedTransaction(
    id: 14,
    title: 'Julian B',
    description: 'Monthly Rent',
    accountId: 2,
    recurrenceId: 2,
    categoryId: 1,
    amount: 600.0,
    credit: true, 
    plannedDate: '2019-09-10T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 15,
    title: 'Betty B',
    description: 'Monthly Rent',
    accountId: 2,
    recurrenceId: 2,
    categoryId: 1,
    amount: 580.0,
    credit: true, 
    plannedDate: '2019-09-04T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 16,
    title: 'Jim B',
    description: 'Monthly Rent',
    accountId: 2,
    recurrenceId: 2,
    categoryId: 1,
    amount: 650.0,
    credit: true, 
    plannedDate: '2019-10-07T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 17,
    title: 'Gas B',
    description: 'Gas Bill House B',
    accountId: 2,
    recurrenceId: 2,
    categoryId: 3,
    amount: 35.0,
    credit: false, 
    plannedDate: '2019-10-03T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 18,
    title: 'Electric B',
    description: 'Electric Bill House B',
    accountId: 2,
    recurrenceId: 2,
    categoryId: 3,
    amount: 50.0,
    credit: false, 
    plannedDate: '2019-10-04T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 19,
    title: 'Internet B',
    description: 'Internet House B',
    accountId: 2,
    recurrenceId: 2,
    categoryId: 3,
    amount: 25.0,
    credit: false, 
    plannedDate: '2019-10-12T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 20,
    title: 'Council Tax B',
    description: 'Council Tax House B',
    accountId: 2,
    recurrenceId: 2,
    categoryId: 3,
    amount: 130.0,
    credit: false, 
    plannedDate: '2019-10-18T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 21,
    title: 'Water Rates B',
    description: 'Water Rates House B',
    accountId: 2,
    recurrenceId: 2,
    categoryId: 3,
    amount: 80.0,
    credit: false, 
    plannedDate: '2019-10-01T00:00:00.000000',
    useForCashFlow: true,
  ),
  PlannedTransaction(
    id: 22,
    title: 'Cleaning B',
    description: 'Cleaning House B',
    accountId: 2,
    recurrenceId: 1,
    categoryId: 4,
    amount: 35.0,
    credit: false, 
    plannedDate: '2019-10-07T00:00:00.000000',
    useForCashFlow: true,
  ), 
  PlannedTransaction(
    id: 23,
    title: 'Mortgage B',
    description: 'Mortgage for House B',
    accountId: 2,
    recurrenceId: 2,
    categoryId: 2,
    amount: 1500.0,
    credit: false, 
    plannedDate: '2019-10-28T00:00:00.000000',
    useForCashFlow: true,
  ), 
  PlannedTransaction(
    id: 24,
    title: 'Boiler Service B',
    description: 'Boiler Service B',
    accountId: 2,
    recurrenceId: 4,
    categoryId: 5,
    amount: 200.0,
    credit: false, 
    plannedDate: '2019-10-01T00:00:00.000000',
    useForCashFlow: true,
  ),
  PlannedTransaction(
    id: 25,
    title: 'Cathy C',
    description: 'Monthly Rent',
    accountId: 3,
    recurrenceId: 2,
    categoryId: 1,
    amount: 680.0,
    credit: true, 
    plannedDate: '2019-09-03T00:00:00.000000',
    useForCashFlow: true,
  ),  
  PlannedTransaction(
    id: 26,
    title: 'Will C',
    description: 'Monthly Rent',
    accountId: 3,
    recurrenceId: 2,
    categoryId: 1,
    amount: 650.0,
    credit: true, 
    plannedDate: '2019-09-15T00:00:00.000000',
    useForCashFlow: true,
  ),
  PlannedTransaction(
    id: 27,
    title: 'Albert C',
    description: 'Monthly Rent',
    accountId: 3,
    recurrenceId: 2,
    categoryId: 1,
    amount: 695.0,
    credit: true, 
    plannedDate: '2019-09-08T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 28,
    title: 'Julie C',
    description: 'Monthly Rent',
    accountId: 3,
    recurrenceId: 2,
    categoryId: 1,
    amount: 580.0,
    credit: true, 
    plannedDate: '2019-09-12T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 29,
    title: 'Paul C',
    description: 'Monthly Rent',
    accountId: 3,
    recurrenceId: 2,
    categoryId: 1,
    amount: 565.0,
    credit: true, 
    plannedDate: '2019-10-16T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 30,
    title: 'Gas C',
    description: 'Gas Bill House C',
    accountId: 3,
    recurrenceId: 2,
    categoryId: 3,
    amount: 45.0,
    credit: false, 
    plannedDate: '2019-10-05T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 31,
    title: 'Electric C',
    description: 'Electric Bill House C',
    accountId: 3,
    recurrenceId: 2,
    categoryId: 3,
    amount: 50.0,
    credit: false, 
    plannedDate: '2019-10-05T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 32,
    title: 'Internet C',
    description: 'Internet House C',
    accountId: 3,
    recurrenceId: 2,
    categoryId: 3,
    amount: 25.0,
    credit: false, 
    plannedDate: '2019-10-10T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 33,
    title: 'Council Tax C',
    description: 'Council Tax House C',
    accountId: 3,
    recurrenceId: 2,
    categoryId: 3,
    amount: 180.0,
    credit: false, 
    plannedDate: '2019-10-21T00:00:00.000000',
    useForCashFlow: true,
  ),
    PlannedTransaction(
    id: 34,
    title: 'Water Rates C',
    description: 'Water Rates House C',
    accountId: 3,
    recurrenceId: 2,
    categoryId: 3,
    amount: 100.0,
    credit: false, 
    plannedDate: '2019-10-01T00:00:00.000000',
    useForCashFlow: true,
  ),
  PlannedTransaction(
    id: 35,
    title: 'Cleaning C',
    description: 'Cleaning House C',
    accountId: 3,
    recurrenceId: 1,
    categoryId: 4,
    amount: 50.0,
    credit: false, 
    plannedDate: '2019-10-07T00:00:00.000000',
    useForCashFlow: true,
  ), 
  PlannedTransaction(
    id: 36,
    title: 'Mortgage C',
    description: 'Mortgage for House C',
    accountId: 3,
    recurrenceId: 2,
    categoryId: 2,
    amount: 2000.0,
    credit: false, 
    plannedDate: '2019-10-27T00:00:00.000000',
    useForCashFlow: true,
  ), 
  PlannedTransaction(
    id: 37,
    title: 'Boiler Service C',
    description: 'Boiler Service C',
    accountId: 3,
    recurrenceId: 4,
    categoryId: 5,
    amount: 200.0,
    credit: false, 
    plannedDate: '2019-10-01T00:00:00.000000',
    useForCashFlow: true,
  ),
  PlannedTransaction(
    id: 38,
    title: 'Landlord Holiday',
    description: 'Away for a rest',
    accountId: 4,
    recurrenceId: 3,
    categoryId: 6,
    amount: 3000.0,
    credit: false, 
    plannedDate: '2019-01-01T00:00:00.000000',
    useForCashFlow: true,
  ), 
  PlannedTransaction(
    id: 39,
    title: 'Car Tax Annual',
    description: 'Away for a rest',
    accountId: 4,
    recurrenceId: 4,
    categoryId: 7,
    amount: 180.0,
    credit: false, 
    plannedDate: '2019-09-08T00:00:00.000000',
    useForCashFlow: true,
  ),
  PlannedTransaction(
    id: 40,
    title: 'Car Lease',
    description: 'Lease cost per month',
    accountId: 4,
    recurrenceId: 2,
    categoryId: 7,
    amount: 300.0,
    credit: false, 
    plannedDate: '2019-09-10T00:00:00.000000',
    useForCashFlow: true,
  ),
   PlannedTransaction(
    id: 41,
    title: 'Car Petrol',
    description: 'filling up each week',
    accountId: 4,
    recurrenceId: 1,
    categoryId: 7,
    amount: 40.0,
    credit: false, 
    plannedDate: '2019-01-01T00:00:00.000000',
    useForCashFlow: true,
  ),
   PlannedTransaction(
    id: 42,
    title: 'Car Insurance',
    description: 'insurance to drive',
    accountId: 4,
    recurrenceId: 4,
    categoryId: 7,
    amount: 400.0,
    credit: false, 
    plannedDate: '2019-07-09T00:00:00.000000',
    useForCashFlow: true,
  ),
         
];

final TRANSFERS = [
  Transfer(
    id: 1,
    title: 'From A to Savings',
    description: 'to landlord account',
    fromAccountId: 1,
    toAccountId: 4,
    amount: 500.0,
    plannedDate: '2019-10-20T00:00:00.000000',
    recurrenceId: 2,
  ),
  Transfer(
    id: 2,
    title: 'From B to Savings',
    description: 'to landlord account',
    fromAccountId: 2,
    toAccountId: 4,
    amount: 500.0,
    plannedDate: '2019-10-20T00:00:00.000000',
    recurrenceId: 2,
  ),
  Transfer(
    id: 3,
    title: 'From C to Savings',
    description: 'to landlord account',
    fromAccountId: 3,
    toAccountId: 4,
    amount: 500.0,
    plannedDate: '2019-10-20T00:00:00.000000',
    recurrenceId: 2,
  ),    
];